Diesel-Jeans/signal

- Cargo.toml
- client/src/main.rs
Fixes an issue with the workspaces by specifying the resolver
> Specifying workspace resolver

- client/src/client.rs
- client/src/client_common.rs
- client/src/contact.rs
- client/src/main.rs
- client/src/server.rs
basic structures for client, server and contacts aswell as encryption
> Basic structure and encryption

- .gitignore
- client/src/contact_manager.rs
- client/src/encryption.rs
- client/src/key_management/bundle.rs
- client/src/main.rs
- client/src/storage.rs
* Added struct to enable serialization
* Updated gitignore
* Implemented saving and loading device data
> Implemented storage on device

- Cargo.lock
- client/src/key_management/key_manager.rs
- common/src/lib.rs
- common/src/pre_key.rs
- server/Cargo.toml
- server/src/server.rs
Closes #31
Point of this endpoint is to check if the client and server has the same keys for the client.
> Endpoint: keys/check

- server/src/server.rs
Closes #38
Added the endpoint getting the amount of pre keys available for a specific user.
> GET: v2/keys

- common/src/web_api.rs
- server/src/server.rs
Closes #37 
Now has endpoint for getting another users public keys
> GET: /v2/keys/{identifier}/{device_id}

- client/src/contact_manager.rs
- client/src/encryption.rs
- client/src/key_management/bundle.rs
- client/src/key_management/key_manager.rs
- client/src/storage.rs
- common/src/pre_key.rs
- server/src/in_memory_db.rs
- server/src/server.rs
Also ran cargo clippy --fix hence the many file edits.
> Added generation of identity key for the client.

- client/src/contact_manager.rs
- client/src/key_management/key_manager.rs
- common/src/web_api.rs
- server/database/init.sql
- server/src/account.rs
- server/src/database.rs
- server/src/in_memory_db.rs
- server/src/managers/key_manager.rs
- server/src/postgres.rs
- server/src/server.rs
* GET: Keys, fetching a users keys; Fixes #42 
* POST: check keys, checking the servers keys vs. the users; Fixes #41
> Adding endpoints for crypto keys

- server/src/account.rs
- server/src/managers/state.rs
- server/src/postgres.rs
- server/src/server.rs
> Removed keys from device

- Cargo.lock
- common/src/web_api/mod.rs
- server/Cargo.toml
- server/database/init.sql
- server/src/account.rs
- server/src/account_authenticator.rs
- server/src/main.rs
- server/src/managers/account_manager.rs
- server/src/postgres.rs
- server/src/server.rs
- server/src/socket.rs
Added authentication, which can be added to any endpoint
Closes #32
> Added AuthenticatedDevice

- common/src/web_api/mod.rs
- server/database/init.sql
- server/src/account.rs
- server/src/account_authenticator.rs
- server/src/database.rs
- server/src/in_memory_db.rs
- server/src/managers/client_presence_manager.rs
- server/src/managers/key_manager.rs
- server/src/managers/state.rs
- server/src/message_cache.rs
- server/src/postgres.rs
- server/src/server.rs
- server/src/socket.rs
> Put keys endpoint

- Cargo.lock
- server/Cargo.toml
- server/src/account.rs
- server/src/managers/state.rs
- server/src/managers/websocket/connection.rs
- server/src/managers/websocket/net_helper.rs
- server/src/managers/websocket/websocket_manager.rs
- server/src/postgres.rs
- server/src/server.rs
- server/src/test_utils/user.rs
Added web socket routing.
We have to figure out how to delete messages after they have been sent.
Closes #80
> Added web socket routing

- server/src/account_authenticator.rs
- server/src/managers/account_manager.rs
- server/src/managers/key_manager.rs
- server/src/managers/message_persister.rs
- server/src/managers/state.rs
- server/src/managers/websocket/websocket_manager.rs
- server/src/server.rs
> Fix state architecture

- server/src/postgres.rs
- server/src/test_utils/database.rs
Formatted based on https://sqlformat.org/ as a standart.
> Formatted all the sql statements

- server/src/server.rs
- Added `WebSocketConnection `as `MessageAvailabilityListener `to `MessageManager`
- Server now sends all cached and stored messages to client when they connect
closes #113
> Added WS Connection to MessageManager

- client/src/client.rs
- client/src/server.rs
- client/src/websockets.rs
> Ws send message

- client/src/client.rs
- client/src/contact_manager.rs
- client/src/encryption.rs
- client/src/key_management/bundle.rs
- client/src/key_management/key_manager.rs
- client/src/server.rs
- client/src/storage.rs
- client/src/websockets.rs
- common/src/web_api/authorization.rs
- common/src/web_api/mod.rs
- server/src/account.rs
- server/src/database.rs
- server/src/destination_device_validator.rs
- server/src/managers/account_manager.rs
- server/src/managers/key_manager.rs
- server/src/managers/message_persister.rs
- server/src/managers/messages_manager.rs
- server/src/managers/websocket/connection.rs
- server/src/managers/websocket/net_helper.rs
- server/src/managers/websocket/websocket_manager.rs
- server/src/message_cache.rs
- server/src/postgres.rs
- server/src/test_utils/message_cache.rs
- server/src/test_utils/websocket.rs
* Postgres now use Protocol address instead of its components #115 
* Removed unused imports
* Changed some functions to use more lazy functions or changed to a more idiomatic way
* Fixed todo, which now causes the add_device function on account to check if incoming is already contained, returns and error if true
> Refactoring

- server/src/managers/client_presence_manager.rs
- server/src/managers/state.rs
- server/src/managers/websocket/connection.rs
- server/src/server.rs
> Integrated ClientPresenceManager

- Cargo.lock
- client/src/client.rs
- client/src/errors.rs
- client/src/main.rs
- client/src/persistent_receiver.rs
- client/src/server.rs
This pull request introduces several significant changes to the `client` module, including the addition of a new `PersistentReceiver` struct, updates to error handling, and modifications to the `ServerAPI` implementation to support WebSocket connections. The most important changes are summarized below:
* Added a new `WebSocketError` variant to the `SignalClientError` enum and updated the `fmt::Display` implementation to handle it.
* Introduced the `PersistentReceiver` struct in a new file `client/src/persistent_receiver.rs`, which facilitates receiving messages with optional filtering. Included unit tests to validate its functionality.
* Updated the `ServerAPI` to include a `PersistentReceiver` for handling incoming WebSocket messages and modified the `connect` method to establish …
> Integration of WebSocket on Client

- client/src/client.rs
- client/src/errors.rs
- client/src/key_manager.rs
- client/src/main.rs
- client/src/server.rs
- client/src/storage/generic.rs
- common/src/web_api/mod.rs
- server/src/account.rs
- server/src/managers/account_manager.rs
- server/src/managers/key_manager.rs
- server/src/postgres.rs
- server/src/server.rs
- server/src/test_utils/database.rs
- server/src/test_utils/user.rs
I have implemented the client functionality to put ones keys to the server, and to fetch ones prekey bundle when doing the pqxdh, over and out :shipit: 
closes #165 #164
> implemented put and fetch keys api client side

- Cargo.lock
- common/Cargo.toml
- common/src/web_api/mod.rs
Made keys base64 using serde_with
> Make keys base64
